name: First Workflow
on: workflow_dispatch
jobs:
  First_Job:
    runs-on: ubuntu-latest
    steps:
      - name: "Step1"
        run: echo "Hello World!"
      - name: "Step2"
        run: echo "Good Bye"

